Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2020-06, with the labels that each got.

#90 Vendor gardener/gardener@b50098267f2577d06674903fa20032f1fe44894b
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/backupentry/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/infrastructure/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/reconciler.go
  vendor/github.com/gardener/gardener/pkg/apis/core/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.pb.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/generated.proto
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/types_seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/apis/core/validation/seed.go
  vendor/github.com/gardener/gardener/pkg/apis/core/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/istio/ingress_gateway.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/types.go
  vendor/modules.txt
Labels: area/open-source, kind/bug, needs/ok-to-test, platform/openstack, priority/normal

#91 [ci:component:github.com/gardener/machine-controller-manager:v0.29.0->v0.30.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#88 [ci:component:github.com/gardener/terraformer:v1.0.0->v1.1.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#94 fix infrastructure validation for router id
  pkg/apis/openstack/validation/infrastructure.go
Labels: reviewed/ok-to-test

#95 fixed tests for router id pointer
  pkg/apis/openstack/validation/infrastructure_test.go
  pkg/internal/infrastructure/terraform_test.go
Labels: reviewed/ok-to-test

#98 Add region information to cloud-provider config
  charts/internal/cloud-provider-config/templates/_cloud-provider-config-global.tpl
  charts/internal/cloud-provider-config/values.yaml
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
Labels: area/usability, kind/enhancement, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm

#100 Nit: Unify using k8s.io/utils/pointer pkg
  pkg/apis/openstack/validation/cloudprofile_test.go
Labels: needs/ok-to-test, reviewed/lgtm

#101 Wait for terraformer before deleting infrastructure
  go.mod
  go.sum
  pkg/controller/infrastructure/actuator_delete.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/config.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/state.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/types.go
  vendor/github.com/gardener/gardener/extensions/pkg/terraformer/waiter.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/defaults.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/defaults.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/health_check.go
  vendor/modules.txt
Labels: area/quality, area/robustness, kind/bug, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm

#103 [ci:component:github.com/gardener/terraformer:v1.1.0->v1.2.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#104 [ci:component:github.com/gardener/machine-controller-manager:v0.30.0->v0.31.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#102 Workaround storage class changes
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, needs/review, platform/openstack, priority/normal

#105 Remove testgrid links to tests with kubernetes version < 1.15
  README.md
Labels: area/documentation, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm

#106 Adjust version disclaimer message
  README.md
Labels: area/documentation, needs/ok-to-test, platform/openstack, priority/normal

#92 Allow to configure subnet which a router should be attached to
  charts/internal/openstack-infra/templates/main.tf
  charts/internal/openstack-infra/values.yaml
  docs/usage-as-end-user.md
  example/30-infrastructure.yaml
  hack/api-reference/api.md
  pkg/apis/openstack/types_infrastructure.go
  pkg/apis/openstack/v1alpha1/types_infrastructure.go
  pkg/apis/openstack/v1alpha1/zz_generated.conversion.go
  pkg/apis/openstack/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/openstack/validation/infrastructure.go
  pkg/apis/openstack/validation/infrastructure_test.go
  pkg/apis/openstack/zz_generated.deepcopy.go
  pkg/internal/infrastructure/terraform.go
  pkg/internal/infrastructure/terraform_test.go
Labels: kind/enhancement, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm

#108 Remove NoExecute toleration from CCM
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm

#110 Nit: Add missing CRD under example/
  README.md
  example/20-crd-controlplane.yaml
Labels: area/open-source, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm

#111 add rolling update strategy to deployment
  charts/gardener-extension-provider-openstack/templates/deployment.yaml
  charts/gardener-extension-provider-openstack/values.yaml
  example/controller-registration.yaml
Labels: kind/technical-debt, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm

#112 Adapt to terraform v0.12 language changes
  charts/internal/openstack-infra/templates/main.tf
  charts/internal/openstack-infra/templates/variables.tf
  charts/internal/openstack-infra/values.yaml
  docs/usage-as-end-user.md
  pkg/internal/infrastructure/terraform.go
  pkg/internal/infrastructure/terraform_test.go
Labels: kind/cleanup, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm

#113 Delete running terraformer Pods before deleting infrastructure
  pkg/controller/infrastructure/actuator_delete.go
Labels: area/quality, area/robustness, kind/bug, needs/ok-to-test, needs/review, platform/openstack, priority/normal

#116 [ci:component:github.com/gardener/terraformer:v1.2.0->v1.3.0]
  charts/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm

#117 Skip `StorageClass` cleanup for hibernated shoots
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: area/usability, kind/bug, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm
