Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2020-05, with the labels that each got.

#70 Add sideEffects for admission assets
  charts/gardener-extension-validator-openstack/charts/application/templates/validatingwebhook-validator.yaml
  example/40-validatingwebhookconfiguration.yaml
Labels: needs/ok-to-test

#71 [ci:component:github.com/gardener/machine-controller-manager:v0.27.0->v0.28.0]
  charts/images.yaml
Labels: needs/ok-to-test

#72 Vendor gardener/gardener@v1.4.1
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/github.com/gardener/gardener/pkg/gardenlet/apis/config/types.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/constraints_check.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/health_check.go
  vendor/github.com/gardener/gardener/pkg/utils/validation/cidr/disjoint.go
  vendor/modules.txt
Labels: needs/ok-to-test

#74 use first load balancer class as default if no class with name "default" provided
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
Labels: needs/ok-to-test

#75 Use workqueue backoff
  pkg/controller/infrastructure/actuator_reconcile.go
Labels: area/quality, kind/enhancement, needs/ok-to-test, needs/review, priority/normal, size/xs

#77 Prevent errors to be logged multiple times
  pkg/controller/infrastructure/actuator_reconcile.go
Labels: needs/ok-to-test, reviewed/lgtm

#78 [ci:component:github.com/gardener/machine-controller-manager:v0.28.0->v0.29.0]
  charts/images.yaml
Labels: needs/ok-to-test

#81 Vendor gardener/gardener@4949b41172cc35f6fecf920d6f7151b24562ae75
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/backupbucket/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/backupentry/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/github.com/gardener/gardener/pkg/features/features.go
  vendor/github.com/gardener/gardener/pkg/gardenlet/features/features.go
  vendor/github.com/gardener/gardener/pkg/operation/common/types.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/istio/crds.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/istio/ingress_gateway.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/istio/istiod.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/istio/type.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/modules.txt
Labels: area/open-source, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#76 add domain field to floatingpool and validate it
  charts/gardener-extension-validator-openstack/charts/application/templates/rbac.yaml
  docs/usage-as-operator.md
  hack/api-reference/api.md
  pkg/apis/openstack/types_cloudprofile.go
  pkg/apis/openstack/v1alpha1/types_cloudprofile.go
  pkg/apis/openstack/v1alpha1/zz_generated.conversion.go
  pkg/apis/openstack/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/openstack/validation/cloudprofile.go
  pkg/apis/openstack/validation/cloudprofile_test.go
  pkg/apis/openstack/validation/controlplane.go
  pkg/apis/openstack/validation/controlplane_test.go
  pkg/apis/openstack/validation/infrastructure.go
  pkg/apis/openstack/validation/infrastructure_test.go
  pkg/apis/openstack/zz_generated.deepcopy.go
  pkg/internal/credentials.go
  pkg/validator/shoot_handler.go
  pkg/validator/shoot_validator.go
Labels: area/usability, kind/api-change, needs/ok-to-test, reviewed/lgtm, size/m

#82 Vendor gardener/gardener@28def0ceecf15f5c7323cd5e65300adc0b0c81da
  cmd/gardener-extension-provider-openstack/app/app.go
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/backupentry/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/pkg/scheduler/controller/shoot/scheduler_control.go
  vendor/modules.txt
Labels: area/open-source, kind/enhancement, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm

#83 Vendor gardener/gardener@v1.5.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: area/open-source, kind/enhancement, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm

#84 Move credentials methods from pkg/internal to pkg/openstack
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/worker/machines.go
  pkg/internal/infrastructure/infrastructure.go
  pkg/internal/infrastructure/terraform.go
  pkg/internal/infrastructure/terraform_test.go
  pkg/internal/terraform.go
  pkg/internal/terraform_test.go
  pkg/openstack/client/swift.go
  pkg/openstack/credentials.go
  pkg/validator/shoot_handler.go
  pkg/validator/shoot_validator.go
Labels: area/quality, kind/bug, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm

#85 Fix status.lastError.codes for Infrastructure
  pkg/controller/infrastructure/actuator_reconcile.go
Labels: area/quality, kind/bug, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm

#86 Vendor gardener/gardener@v1.5.1
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_migrate.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/botanist.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/cleanup.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/containerruntime.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/dns/dnsentry.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/dns/dnsprovider.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/extension.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/infrastructure.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/network.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/operatingsystemconfig.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/waiter.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/worker.go
  vendor/github.com/gardener/gardener/pkg/operation/common/extensions.go
  vendor/github.com/gardener/gardener/pkg/operation/operation.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/health/health.go
  vendor/github.com/gardener/gardener/pkg/utils/retry/retry.go
  vendor/github.com/gardener/gardener/test/framework/dump.go
  vendor/modules.txt
Labels: area/quality, kind/enhancement, needs/ok-to-test, platform/openstack, priority/normal
