Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2021-02, with the labels that each got.

#217 Fix ControlPlane reconciliation for K8s < 1.19
  charts/images.yaml
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#207 update machineclasses to use cloudprovider secret
  charts/internal/machineclass/templates/machineclass.yaml
  charts/internal/machineclass/values.yaml
  pkg/controller/worker/machine_controller_manager.go
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
  pkg/openstack/types.go
  pkg/webhook/cloudprovider/ensurer.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm, size/m

#223 VPA for validator/admission component
  charts/gardener-extension-validator-openstack/charts/runtime/templates/vpa.yaml
  charts/gardener-extension-validator-openstack/values.yaml
Labels: area/auto-scaling, area/scalability, kind/enhancement, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm, size/s

#226 Secret data checksum for CSI driver on worker nodes
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
Labels: area/usability, kind/bug, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm, size/xs

#218 Add useragent header for api call issued by ccm and csi driver
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/deployment-csi-driver-controller.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm, size/m

#228 Vendor gardener/gardener@v1.16.3
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  vendor/github.com/gardener/gardener/hack/install-promtool.sh
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/github.com/gardener/gardener/pkg/utils/imagevector/imagevector.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#229 [release-v1.16] Vendor gardener/gardener@v1.16.3
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_delete.go
  vendor/github.com/gardener/gardener/hack/install-promtool.sh
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/errors.go
  vendor/github.com/gardener/gardener/pkg/operation/seed/seed.go
  vendor/github.com/gardener/gardener/pkg/utils/imagevector/imagevector.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#230 [release-v1.16] Secret data checksum for CSI driver on worker nodes
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
Labels: area/usability, kind/bug, needs/ok-to-test, needs/review, platform/openstack, priority/normal, size/xs

#231 [release-v1.16] [ci:component:github.com/gardener/terraformer:v2.1.0->v2.1.1]
  charts/images.yaml
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#222 Add max retries to repeat failed or throttled operations
  charts/internal/openstack-infra/templates/main.tf
  charts/internal/openstack-infra/values.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, platform/openstack, priority/normal, reviewed/lgtm, size/xs

#233 Update kubernetes-csi/external-snapshotter to v2.1.4
  charts/images.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs
