Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2021-05, with the labels that each got.

#274 Do not print secret content in error message
  pkg/openstack/credentials.go
Labels: kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#276 [release-v1.17] Automated cherry pick of #274: Do not print secret content in error message
  pkg/openstack/credentials.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#275 [release-v1.16] Automated cherry pick of #274: Do not print secret content in error message
  pkg/openstack/credentials.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#277 Prepare next dev cycle v1.18.1-dev
  VERSION
  example/controller-registration.yaml
Labels: needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#278 [release-v1.18] Automated cherry pick of #274: Do not print secret content in error message
  pkg/openstack/credentials.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#281 Upgrade machine-controller-manager-provider-openstack
  charts/images.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#280 Add validation for cloud provider Secrets
  charts/gardener-extension-admission-openstack/charts/application/templates/validatingwebhook-validator.yaml
  cmd/gardener-extension-admission-openstack/app/app.go
  docs/local-setup.md
  example/40-validatingwebhookconfiguration.yaml
  hack/dev-setup-admission-openstack.sh
  pkg/admission/validator/secrets.go
  pkg/admission/validator/shoot.go
  pkg/admission/validator/webhook.go
  pkg/apis/openstack/validation/secrets.go
  pkg/apis/openstack/validation/secrets_test.go
  pkg/internal/infrastructure/infrastructure.go
  pkg/openstack/credentials.go
  vendor/github.com/gardener/gardener/extensions/pkg/util/index/index.go
  vendor/github.com/gardener/gardener/extensions/pkg/util/secret/secret.go
  vendor/modules.txt
Labels: area/ops-productivity, area/robustness, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/do-not-merge, reviewed/lgtm, size/l

#282 use go templates for terraform
  charts/internal/openstack-infra/Chart.yaml
  charts/internal/openstack-infra/templates/_helpers.tpl
  charts/internal/openstack-infra/values.yaml
  go.mod
  pkg/controller/infrastructure/actuator.go
  pkg/controller/infrastructure/actuator_reconcile.go
  pkg/internal/infrastructure/template.go
  pkg/internal/infrastructure/template_test.go
  pkg/internal/infrastructure/templates/main.tpl.tf
  pkg/internal/infrastructure/templates/terraform.tfvars
  pkg/internal/infrastructure/templates/variables.tf
  pkg/internal/infrastructure/terraform.go
  pkg/internal/infrastructure/terraform_test.go
  vendor/modules.txt
Labels: area/control-plane, kind/cleanup, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/m

#286 Vendor gardener/gardener@v1.23.1
  example/controller-registration.yaml
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/charts/images.yaml
  vendor/github.com/gardener/gardener/hack/generate-controller-registration.sh
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types.go
  vendor/modules.txt
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#288 Reduce the log level of cinder-csi-driver
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
Labels: kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#291 Update the admission-openstack RBAC after cloud provider Secrets validation feature
  charts/gardener-extension-admission-openstack/charts/application/templates/rbac.yaml
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#290 Remove version constraints for lb config
  go.mod
  pkg/admission/validator/shoot.go
  pkg/apis/openstack/helper/helper.go
  pkg/apis/openstack/helper/helper_test.go
  pkg/apis/openstack/validation/controlplane.go
  pkg/apis/openstack/validation/controlplane_test.go
  pkg/controller/controlplane/valuesprovider.go
  vendor/modules.txt
Labels: kind/cleanup, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/m

#292 [release-v1.19] Remove version constraints for lb config
  go.mod
  pkg/admission/validator/shoot.go
  pkg/apis/openstack/helper/helper.go
  pkg/apis/openstack/helper/helper_test.go
  pkg/apis/openstack/validation/controlplane.go
  pkg/apis/openstack/validation/controlplane_test.go
  pkg/controller/controlplane/valuesprovider.go
  vendor/modules.txt
Labels: kind/cleanup, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/m

#287 Update kubernetes-csi/livenessprobe
  charts/images.yaml
Labels: kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#289 Expose logs from user exposed components in the new way
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/configmap-observability.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/configmap-observability.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs
