Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2021-07, with the labels that each got.

#301 Add a link to the cherry-pick-pr script from gardener
  Makefile
  hack/cherry-pick-pull.sh
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#302 Make leader election resource lock configurable and default to leases
  charts/gardener-extension-provider-openstack/templates/deployment.yaml
  charts/gardener-extension-provider-openstack/values.yaml
  cmd/gardener-extension-provider-openstack/app/app.go
  example/controller-registration.yaml
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#303 correct typo
  docs/usage-as-end-user.md
Labels: needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#300 add support for application credentials
  Dockerfile
  charts/internal/cloud-provider-config/templates/_cloud-provider-config-global.tpl
  charts/internal/cloud-provider-config/values.yaml
  docs/usage-as-end-user.md
  pkg/apis/openstack/validation/secrets.go
  pkg/apis/openstack/validation/secrets_test.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
  pkg/controller/infrastructure/actuator_delete.go
  pkg/controller/infrastructure/actuator_reconcile.go
  pkg/internal/infrastructure/templates/main.tpl.tf
  pkg/internal/infrastructure/templates/variables.tf
  pkg/internal/terraform.go
  pkg/internal/terraform_test.go
  pkg/openstack/client/client.go
  pkg/openstack/credentials.go
  pkg/openstack/types.go
Labels: area/control-plane, area/security, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/do-not-merge, reviewed/lgtm, reviewed/ok-to-test, size/xl

#311 Set minAllowed memory for csi-driver-node containers
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#309 Clean up handling for unsupported K8s versions
  README.md
  charts/gardener-extension-provider-openstack/templates/_helpers.tpl
  charts/images.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/_helpers.tpl
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/configmap-observability.yaml
  charts/internal/shoot-storageclasses/templates/_helpers.tpl
  charts/internal/shoot-storageclasses/templates/storageclasses_legacy.yaml
  example/10-fake-shoot-controlplane.yaml
  example/30-controlplane.yaml
  example/30-worker.yaml
  example/controller-registration.yaml
  pkg/controller/controlplane/valuesprovider_test.go
  test/e2e/netpol-gen/app/openstack.go
  test/e2e/networkpolicies/networkpolicy_test.go
Labels: kind/cleanup, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/m

#313 restrict app credentials to 1.19+
  pkg/admission/validator/shoot.go
  pkg/apis/openstack/validation/shoot.go
  pkg/apis/openstack/validation/shoot_test.go
Labels: area/control-plane, kind/bug, merge/squash, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/s

#306 fix server group removal from worker pool
  pkg/controller/worker/machine_dependencies.go
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
  pkg/controller/worker/server_groups.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/m

#315 push component-descriptor on head update
  .ci/pipeline_definitions
Labels: area/ops-productivity, kind/task, needs/ok-to-test, needs/review, platform/openstack, size/xs

#316 update docs for application credentials
  docs/usage-as-end-user.md
Labels: area/documentation, kind/enhancement, needs/lgtm, needs/ok-to-test, needs/review, platform/openstack, size/xs

#318 Add release milestone check action
  .github/workflows/release-milestone.yaml
Labels: kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/s

#310 Improve LoadBalancerClass validation
  pkg/apis/openstack/cloudprofile_test.go
  pkg/apis/openstack/openstack_suite_test.go
  pkg/apis/openstack/types_cloudprofile.go
  pkg/apis/openstack/validation/cloudprofile.go
  pkg/apis/openstack/validation/cloudprofile_test.go
  pkg/apis/openstack/validation/controlplane.go
Labels: kind/api-change, kind/enhancement, merge/squash, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/l

#319 Expose MCM logs to the end-users
  charts/gardener-extension-provider-openstack/templates/configmap-logging.yaml
  example/controller-registration.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs
