Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2021-04, with the labels that each got.

#255 Update kubernetes-csi/external-snapshotter
  charts/images.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#256 Update kubernetes-csi/livenessprobe
  charts/images.yaml
Labels: kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#257 [release-v1.17] Automated cherry pick of #256: Update kubernetes-csi/livenessprobe
  charts/images.yaml
Labels: kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#258 [release-v1.16] Automated cherry pick of #256: Update kubernetes-csi/livenessprobe
  charts/images.yaml
  go.sum
Labels: kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/s

#261 Switch to kaniko oci builder
  .ci/pipeline_definitions
  Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#264 improve infrastructure config documentation
  docs/usage-as-end-user.md
Labels: needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#259 Specify container resources for CSI sidecars
  charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
Labels: kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#265 Add CloudProfile validator
  .ci/pipeline_definitions
  Dockerfile
  Makefile
  charts/gardener-extension-admission-openstack/.helmignore
  charts/gardener-extension-admission-openstack/Chart.yaml
  charts/gardener-extension-admission-openstack/charts/application/Chart.yaml
  charts/gardener-extension-admission-openstack/charts/application/templates/_helpers.tpl
  charts/gardener-extension-admission-openstack/charts/application/templates/rbac.yaml
  charts/gardener-extension-admission-openstack/charts/application/templates/serviceaccount.yaml
  charts/gardener-extension-admission-openstack/charts/application/templates/validatingwebhook-validator.yaml
  charts/gardener-extension-admission-openstack/charts/application/values.yaml
  charts/gardener-extension-admission-openstack/charts/runtime/Chart.yaml
  charts/gardener-extension-admission-openstack/charts/runtime/templates/_helpers.tpl
  charts/gardener-extension-admission-openstack/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-openstack/charts/runtime/templates/poddisruptionbudget.yaml
  charts/gardener-extension-admission-openstack/charts/runtime/templates/secret-cert.yaml
  charts/gardener-extension-admission-openstack/charts/runtime/templates/secret-kubeconfig.yaml
  charts/gardener-extension-admission-openstack/charts/runtime/templates/service.yaml
  charts/gardener-extension-admission-openstack/charts/runtime/templates/vpa.yaml
  charts/gardener-extension-admission-openstack/charts/runtime/values.yaml
  charts/gardener-extension-admission-openstack/templates/_helpers.tpl
  charts/gardener-extension-admission-openstack/values.yaml
  charts/gardener-extension-validator-openstack/Chart.yaml
  charts/gardener-extension-validator-openstack/charts/application/Chart.yaml
  charts/gardener-extension-validator-openstack/charts/runtime/Chart.yaml
  cmd/gardener-extension-admission-openstack/app/app.go
  cmd/gardener-extension-admission-openstack/main.go
  example/40-validatingwebhookconfiguration.yaml
  example/admission-openstack-certs/tls.crt
  example/admission-openstack-certs/tls.key
  pkg/admission/cmd/options.go
  pkg/admission/validator/cloudprofile.go
  pkg/admission/validator/serialization.go
  pkg/admission/validator/shoot.go
  pkg/admission/validator/webhook.go
  pkg/apis/openstack/validation/cloudprofile.go
  pkg/apis/openstack/validation/cloudprofile_test.go
  pkg/validator/shoot_handler.go
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xl

#266 Clean up the stale target build stage
  Dockerfile
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs

#268 Decrease terraformer log level
  pkg/internal/terraform.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#270 Update MCM logging filter
  charts/gardener-extension-provider-openstack/templates/configmap-logging.yaml
  example/controller-registration.yaml
Labels: area/control-plane, kind/cleanup, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#272 Use occm@v1.21.0 and cinder csi@v1.21.0 for k8s >= v1.21
  charts/images.yaml
Labels: area/open-source, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs
