Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2021-11, with the labels that each got.

#349 Add Kubernetes v1.22 conformance badge
  README.md
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, area/testing

#353 Add docforge manifest
  .docforge/manifest.yaml
Labels: area/documentation, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, platform/openstack, size/xs

#354 Improve the error message when a required part of webhookConfig is missing
  charts/gardener-extension-admission-openstack/charts/application/templates/validatingwebhook-validator.yaml
  charts/gardener-extension-admission-openstack/charts/runtime/templates/secret-cert.yaml
Labels: area/quality, kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#355 use v1.21.0 for K8s >=1.18 <1.22
  charts/images.yaml
Labels: area/control-plane, kind/regression, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs
