Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2022-05, with the labels that each got.

#445 Remove validation avoiding sfz
  pkg/apis/openstack/validation/shoot.go
  pkg/apis/openstack/validation/shoot_test.go
Labels: kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs, area/auto-scaling

#434 Remove deprecated dashboards
  charts/internal/seed-controlplane/charts/cloud-controller-manager/ccm-observability-dashboard.json
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/configmap-observability.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/csi-driver-controller-dashboard.json
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/configmap-observability.yaml
Labels: area/logging, kind/cleanup, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xl

#436 add k8s v1.23 conformance testgrid link
  README.md
Labels: area/certification, kind/test, platform/openstack, reviewed/lgtm, size/xs

#412 Update manifest.yaml
  .docforge/manifest.yaml
Labels: reviewed/lgtm, size/xs

#442 rework component resources
  charts/gardener-extension-admission-openstack/charts/runtime/templates/vpa.yaml
  charts/gardener-extension-provider-openstack/templates/vpa.yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/machine-controller-manager/seed/templates/vpa.yaml
  charts/internal/machine-controller-manager/seed/values.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/vpa.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-vpa.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-controller-vpa.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-validation-webhook-vpa.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/vpa-csi-driver-controller.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
  cmd/gardener-extension-provider-openstack/app/app.go
  example/controller-registration.yaml
  pkg/controller/controlplane/valuesprovider.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/m

#446 Update CCM version to 1.23.1
  charts/images.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#448 [release-v1.25] Automated cherry pick of #446: Update CCM version to 1.23.1
  charts/images.yaml
Labels: area/control-plane, kind/bug, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#449 fix typo in requirements.yaml
  charts/internal/shoot-system-components/requirements.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#440 fix cloud-provider-config generation
  charts/internal/cloud-provider-config/templates/_cloud-provider-config-loadbalancer.tpl
Labels: needs/ok-to-test, reviewed/lgtm

#453 Support for Kubernetes v1.24
  README.md
  charts/images.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/common/checkerwatchdog.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/common/checkerwatchdogfactory.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/common/watchdogmanager.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/util/secret/manager/manager.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/certificates/add.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/certificates/reconciler.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/cmd/options.go
  vendor/github.com/gardener/gardener/hack/test-integration.sh
  vendor/github.com/gardener/gardener/hack/tools.mk
  vendor/github.com/gardener/gardener/pkg/client/kubernetes/client.go
  vendor/github.com/gardener/gardener/pkg/gardenlet/apis/config/types.go
  vendor/github.com/gardener/gardener/pkg/gardenlet/apis/config/v1alpha1/types.go
  vendor/github.com/gardener/gardener/pkg/gardenlet/apis/config/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener/pkg/gardenlet/apis/config/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/gardenlet/apis/config/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/healthz/periodic.go
  vendor/github.com/gardener/gardener/pkg/utils/flow/progress_reporter_delaying.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/health/seed.go
  vendor/github.com/gardener/gardener/pkg/utils/kubernetes/unstructured/object.go
  vendor/github.com/gardener/gardener/pkg/utils/secrets/alias.go
  vendor/github.com/gardener/gardener/pkg/utils/secrets/certificate.go
  vendor/github.com/gardener/gardener/pkg/utils/secrets/manager/manager.go
  vendor/github.com/gardener/gardener/pkg/utils/validation/features/featuregates.go
  vendor/github.com/gardener/gardener/pkg/utils/version/version.go
  vendor/k8s.io/apimachinery/pkg/util/clock/clock.go
  vendor/modules.txt
Labels: area/open-source, area/usability, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#454 Enable the healthchecks for the csi-snapshot-validation Deployment
  pkg/controller/healthcheck/add.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#452 admission-openstack: Adapt Secrets webhook to rely on the provider label
  charts/gardener-extension-admission-openstack/charts/application/templates/rbac.yaml
  charts/gardener-extension-admission-openstack/charts/application/templates/validatingwebhook-validator.yaml
  cmd/gardener-extension-admission-openstack/app/app.go
  example/40-validatingwebhookconfiguration.yaml
  pkg/admission/validator/secretbinding.go
  pkg/admission/validator/secretbinding_test.go
  pkg/admission/validator/secrets.go
  pkg/admission/validator/validator_suite_test.go
  pkg/admission/validator/webhook.go
  vendor/github.com/gardener/gardener/extensions/pkg/util/index/index.go
  vendor/github.com/gardener/gardener/extensions/pkg/util/secret/secret.go
  vendor/modules.txt
Labels: area/cost, area/robustness, kind/enhancement, needs/ok-to-test, needs/review, platform/openstack, size/m
