Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2022-02, with the labels that each got.

#388 Update `csi-driver-cinder` for kubernetes v1.23
  charts/images.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/xs

#390 Vendor gardener/gardener@v1.39.3
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_restore.go
  vendor/github.com/gardener/gardener/pkg/apis/core/helper/helpers.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/secrets.go
  vendor/modules.txt
Labels: kind/bug, needs/review, platform/openstack, size/xs, area/control-plane-migration

#391 [release-v1.23] Automated cherry pick of #390: Vendor gardener/gardener@v1.39.3
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/genericactuator/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_restore.go
  vendor/github.com/gardener/gardener/pkg/apis/core/helper/helpers.go
  vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/secrets.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, needs/review, size/xs, area/control-plane-migration

#369 🛡 Enable `ServiceAccount` token projection and token requestor
  Makefile
  charts/gardener-extension-provider-openstack/templates/deployment.yaml
  charts/gardener-extension-provider-openstack/templates/serviceaccount.yaml
  charts/gardener-extension-provider-openstack/values.yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/machine-controller-manager/seed/templates/serviceaccount.yaml
  charts/internal/machine-controller-manager/seed/values.yaml
  charts/internal/machine-controller-manager/shoot/templates/clusterrolebinding-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/values.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/configmap-observability.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/deployment-csi-driver-controller.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/deployment-csi-snapshot-controller.yaml
  charts/internal/seed-controlplane/values.yaml
  charts/internal/shoot-system-components/charts/cloud-controller-manager/templates/rbac-cloud-controller-manager.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrolebinding-csi-attacher.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrolebinding-csi-provisioner.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrolebinding-csi-resizer.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrolebinding-csi-snapshot-controller.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrolebinding-csi-snapshotter.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/rolebinding-csi-attacher.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/rolebinding-csi-provisioner.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/rolebinding-csi-resizer.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/rolebinding-csi-snapshot-controller.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/rolebinding-csi-snapshotter.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/serviceaccount.yaml
  charts/internal/shoot-system-components/values.yaml
  cmd/gardener-extension-provider-openstack/app/app.go
  example/20-crd-extensions.gardener.cloud_bastions.yaml
  example/controller-registration.yaml
  go.mod
  go.sum
  pkg/controller/controlplane/add.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
  pkg/controller/worker/actuator.go
  pkg/controller/worker/add.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_bastion.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/extensions/crds/templates/crd-bastion.tpl.yaml
  vendor/modules.txt
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xl, merge/squash

#387 Add support for sa token volume projection in admission charts
  charts/gardener-extension-admission-openstack/charts/application/templates/rbac.yaml
  charts/gardener-extension-admission-openstack/charts/application/templates/serviceaccount.yaml
  charts/gardener-extension-admission-openstack/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-openstack/charts/runtime/templates/serviceaccount.yaml
  charts/gardener-extension-admission-openstack/values.yaml
  docs/deployment.md
Labels: area/security, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/m

#393 Vendor gardener/gardener@v1.39.5
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/update.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#394 [release-v1.23] Automated cherry pick of #393: Vendor gardener/gardener@v1.39.5
  example/20-crd-extensions.gardener.cloud_bastions.yaml
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/update.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_bastion.go
  vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener/pkg/operation/botanist/component/extensions/crds/templates/crd-bastion.tpl.yaml
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#396 Update valuesprovider.go
  pkg/controller/controlplane/valuesprovider.go
Labels: needs/ok-to-test, reviewed/lgtm

#400 Fix serviceaccount defaulting during helm upgrade
  charts/gardener-extension-admission-openstack/charts/runtime/templates/deployment.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm

#401 Keep `cloud-controller-manager`'s `ClusterRoleBinding` on deletion
  charts/internal/shoot-system-components/charts/cloud-controller-manager/templates/rbac-cloud-controller-manager.yaml
Labels: area/usability, kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#402 Increase cpu resources for csi-driver
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#403 [release-v1.23] Automated cherry pick of #402: Increase cpu resources for csi-driver
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#404 Vendor gardener/gardener@v1.40.2
  go.mod
  go.sum
  vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_restore.go
  vendor/modules.txt
Labels: kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs
