Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2022-07, with the labels that each got.

#469 Use occm `v1.22.0` for `v1.23.x` shoots
  charts/images.yaml
Labels: kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#471 Use openstack-cloud-controller-manager@v1.23.3 for K8s 1.23 Shoots
  charts/images.yaml
Labels: area/open-source, kind/enhancement, needs/ok-to-test, needs/lgtm, platform/openstack, reviewed/lgtm, size/xs

#472 [release-v1.26] Automated cherry pick of #471: Use openstack-cloud-controller-manager@v1.23.3 for K8s 1.23 Shoots #462: Upgrade github.com/kubernetes/cloud-provider-openstack
  charts/images.yaml
Labels: area/open-source, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#465 Change base image from alpine to distroless
  Dockerfile
Labels: area/open-source, area/security, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#476 Upgrade cinder-csi-plugin
  charts/images.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#475 Update v1.24 conformance test coverage
  README.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#480 Upgrade cinder-csi-plugin
  charts/images.yaml
Labels: area/storage, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs
