Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2022-09, with the labels that each got.

#492 Assign Responsibles for the compliance issues
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/lgtm, needs/review, platform/openstack, size/xs

#474 Adds MaxAllowed for VPA objects
  charts/internal/machine-controller-manager/seed/templates/vpa.yaml
  charts/internal/machine-controller-manager/seed/values.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/vpa.yaml
  charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-vpa.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
Labels: kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/s, area/auto-scaling

#501 Upgrade github.com/kubernetes/cloud-provider-openstack
  charts/images.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/xs

#498 Revert "run shoot cluster without overlay if not explicitly specified"
  charts/gardener-extension-provider-openstack/templates/deployment.yaml
  charts/gardener-extension-provider-openstack/values.yaml
  example/controller-registration.yaml
  go.mod
  go.sum
  pkg/cmd/options.go
  pkg/webhook/network/add.go
  pkg/webhook/network/mutate.go
  vendor/github.com/gardener/gardener-extension-networking-calico/LICENSE.md
  vendor/github.com/gardener/gardener-extension-networking-calico/NOTICE.md
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/doc.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/install/install.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/register.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/types_network.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/defaults.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/doc.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/helper/decode.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/register.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/types_network.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/zz_generated.defaults.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/calico/predicates.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/calico/types.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/network/mutator.go
  vendor/github.com/gardener/gardener/extensions/pkg/webhook/network/network.go
  vendor/modules.txt
Labels: area/networking, kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/m
