Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2023-06, with the labels that each got.

#636 fix incorrect manila values
  charts/gardener-extension-provider-openstack/templates/clusterfilters-logging.yaml
  charts/internal/seed-controlplane/charts/csi-driver-manila-controller/templates/deployment-controller.yaml
  charts/internal/seed-controlplane/charts/csi-driver-manila-controller/templates/vpa-controller.yaml
  example/controller-registration.yaml
  pkg/controller/controlplane/valuesprovider.go
Labels: area/control-plane, kind/regression, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/s

#640 Update external-provisioner to version 3.4.1
  charts/images.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/xs

#639 Remove old and obsolete logging configuration
  charts/gardener-extension-provider-openstack/templates/clusterfilters-logging.yaml
  charts/gardener-extension-provider-openstack/templates/configmap-logging.yaml
  example/controller-registration.yaml
Labels: area/logging, kind/cleanup, needs/ok-to-test, needs/review, platform/openstack, size/s

#638 Set effective version when building images
  Dockerfile
  Makefile
Labels: area/usability, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#642 update cloud provider openstack
  charts/images.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/xs

#635 Clean up ignored volumesnapshot CRDs
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/crd-volumesnapshotclasses.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/crd-volumesnapshotcontents.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/crd-volumesnapshots.yaml
Labels: area/storage, kind/cleanup, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xl

#632 Support for Kubernetes v1.27
  README.md
  charts/images.yaml
  pkg/webhook/controlplane/ensurer.go
  pkg/webhook/controlplane/ensurer_test.go
Labels: area/open-source, area/usability, exp/intermediate, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/m, topology/garden, topology/seed, topology/shoot, merge/squash

#647 [release-v1.35] Automated cherry pick of #646: [ci:component:github.com/gardener/machine-controller-manager:v0.49.2->v0.49.3]
  charts/images.yaml
Labels: area/ops-productivity, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#644 Drop code related to `APIServerSNI` feature gate
  pkg/webhook/controlplaneexposure/ensurer.go
  pkg/webhook/controlplaneexposure/ensurer_test.go
Labels: area/dev-productivity, kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m
