Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2023-03, with the labels that each got.

#582 Update CCM Images
  charts/images.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#585 Update v1.26 conformance test coverage
  README.md
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#583 Add wait-for-csi-node annotation to csi-driver-node Pods
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#584 Switch to the non-deprecated funcs of the WorkerDelegate
  pkg/controller/worker/machine_dependencies.go
  pkg/controller/worker/machine_dependencies_test.go
Labels: kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/xl

#590 Vendor `gardener@1.66.1` and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`
  go.mod
  go.sum
  pkg/controller/healthcheck/add.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/modules.txt
Labels: area/control-plane, kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#591 [release-v1.32] Vendor `gardener@1.65.3` and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`
  go.mod
  go.sum
  pkg/controller/healthcheck/add.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go
  vendor/modules.txt
Labels: area/control-plane, kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#592 Switched from DockerHub to Gardener GCR
  charts/images.yaml
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#593 Switch back to upstream GCR images for `openstack-cloud-controller-manager` and `cinder-csi-plugin`
  charts/images.yaml
Labels: area/networking, area/open-source, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/xs

#589 Make the `csi-snapshot-validation` Service topology-aware
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-validation-webhook-service.yaml
  charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
Labels: area/high-availability, area/networking, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/s

#587 replace kaniko
  .ci/pipeline_definitions
Labels: area/delivery, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/xs

#579 Add machine labels to worker pool
  docs/usage-as-end-user.md
  hack/api-reference/api.md
  pkg/apis/openstack/types_worker.go
  pkg/apis/openstack/v1alpha1/types_worker.go
  pkg/apis/openstack/v1alpha1/zz_generated.conversion.go
  pkg/apis/openstack/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/openstack/validation/shoot.go
  pkg/apis/openstack/validation/shoot_test.go
  pkg/apis/openstack/zz_generated.deepcopy.go
  pkg/controller/worker/machines.go
  pkg/controller/worker/machines_test.go
Labels: area/control-plane, kind/api-change, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/l

#594 update occm lb settings
  charts/internal/cloud-provider-config/templates/_cloud-provider-config-loadbalancer.tpl
  charts/internal/cloud-provider-config/values.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/xs

#598 enable cleanup of snapshots
  .ci/pipeline_definitions
Labels: area/dev-productivity, kind/cleanup, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs
