Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2023-10, with the labels that each got.

#679 Support for Kubernetes v1.28
  README.md
  imagevector/images.yaml
Labels: area/open-source, area/usability, exp/intermediate, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/s, topology/garden, topology/seed, topology/shoot, merge/squash

#678 Allow configuration of etcd storage class reclaimPolicy
  charts/gardener-extension-provider-openstack/templates/storageclass.yaml
  example/controller-registration.yaml
Labels: area/control-plane, area/usability, needs/ok-to-test, reviewed/lgtm, size/xs

#662 Introduce the use of central manifest
  .ci/verify
  .docforge/manifest.yaml
  Makefile
Labels: area/documentation, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/s

#682 Update external-snapshotter to v6.3.1
  imagevector/images.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#677 Remove dependency to specific calico and cilium versions.
  go.mod
  go.sum
  pkg/admission/mutator/shoot.go
  pkg/admission/mutator/shoot_test.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
  vendor/github.com/gardener/gardener-extension-networking-calico/LICENSE.md
  vendor/github.com/gardener/gardener-extension-networking-calico/NOTICE.md
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/doc.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/register.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/types_network.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/defaults.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/doc.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/register.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/types_network.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/zz_generated.defaults.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/calico/predicates.go
  vendor/github.com/gardener/gardener-extension-networking-calico/pkg/calico/types.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/LICENSE.md
  vendor/github.com/gardener/gardener-extension-networking-cilium/NOTICE.md
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/doc.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/register.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/types_network.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/v1alpha1/defaults.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/v1alpha1/doc.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/v1alpha1/register.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/v1alpha1/types_network.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/v1alpha1/zz_generated.defaults.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium/zz_generated.deepcopy.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/cilium/predicates.go
  vendor/github.com/gardener/gardener-extension-networking-cilium/pkg/cilium/types.go
  vendor/modules.txt
Labels: area/networking, kind/technical-debt, needs/ok-to-test, platform/aws, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/m

#683 [release-v1.37] Automated cherry pick of #682: Update external-snapshotter to v6.3.1
  charts/images.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#684 fix: Concourse build badge URL
  README.md
Labels: area/documentation, kind/cleanup, needs/ok-to-test, needs/review, platform/openstack, size/xs

#685 fix charts after revendor
  charts/internal/cloud-provider-config/templates/cloud-provider-config-global.tpl
  charts/internal/cloud-provider-config/templates/cloud-provider-config-loadbalancer.tpl
  charts/internal/cloud-provider-config/templates/cloud-provider-config-meta.tpl
  charts/internal/cloud-provider-config/templates/cloud-provider-config-networking.tpl
  charts/internal/cloud-provider-config/templates/cloud-provider-config-route.tpl
Labels: needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#686 readiness check
  charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-validation-webhook-deployment.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/xs

#687 update image definitions
  imagevector/images.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/xs
