Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2024-01, with the labels that each got.

#703 set COMPONENT_PREFIXES env variable to fix upgrade PRs
  .ci/component_descriptor
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#709 fix makefile script
  Makefile
  hack/dev-setup-admission-openstack.sh
Labels: area/dev-productivity, kind/regression, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/s, status/closed

#708 update image rules
  Makefile
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/xs

#711 Drop Machine Controller Manager management
  charts/gardener-extension-provider-openstack/templates/clusterfilters-logging.yaml
  charts/internal/machine-controller-manager/seed/Chart.yaml
  charts/internal/machine-controller-manager/seed/mcm-monitoring-dashboard.json
  charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml
  charts/internal/machine-controller-manager/seed/templates/clusterrolebinding.yaml
  charts/internal/machine-controller-manager/seed/templates/configmap-monitoring.yaml
  charts/internal/machine-controller-manager/seed/templates/deployment.yaml
  charts/internal/machine-controller-manager/seed/templates/poddisruptionbudget.yaml
  charts/internal/machine-controller-manager/seed/templates/service.yaml
  charts/internal/machine-controller-manager/seed/templates/serviceaccount.yaml
  charts/internal/machine-controller-manager/seed/templates/vpa.yaml
  charts/internal/machine-controller-manager/seed/values.yaml
  charts/internal/machine-controller-manager/shoot/Chart.yaml
  charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/templates/clusterrolebinding-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/templates/role-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/templates/rolebinding-machine-controller-manager.yaml
  charts/internal/machine-controller-manager/shoot/values.yaml
  example/controller-registration.yaml
  imagevector/images.yaml
  pkg/openstack/types.go
Labels: area/open-source, kind/cleanup, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/xl

#712 Support for Kubernetes v1.29
  README.md
  imagevector/images.yaml
Labels: area/open-source, area/usability, exp/intermediate, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/s, topology/garden, topology/seed, topology/shoot, merge/squash
