Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2024-03, with the labels that each got.

#724 Upgrade terraformer in v1.39
  imagevector/images.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#702 Drop support for Shoots with Kubernetes version == 1.24
  README.md
  charts/internal/shoot-system-components/charts/csi-driver-manila/templates/clusterrole-node.yaml
  charts/internal/shoot-system-components/charts/csi-driver-manila/templates/podsecuritypolicy.yaml
  charts/internal/shoot-system-components/charts/csi-driver-manila/values.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-driver.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/podsecuritypolicy.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
  docs/usage/usage.md
  example/10-fake-shoot-controlplane.yaml
  example/30-controlplane.yaml
  example/30-worker.yaml
  imagevector/images.yaml
  pkg/apis/openstack/validation/controlplane_test.go
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
  pkg/controller/worker/machines_test.go
  pkg/webhook/controlplane/ensurer_test.go
Labels: kind/cleanup, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/m

#720 Add Kubernetes v1.29 conformance test badge
  README.md
Labels: area/open-source, kind/enhancement, needs/ok-to-test, needs/review, platform/openstack, size/xs

#714 Use `extensionswebhook.EnsureFileWithPath` instead of custom `appendUniqueFile` func
  pkg/webhook/controlplane/ensurer.go
Labels: kind/cleanup, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/xs

#731 Fix subtarget names of docker-images target
  Makefile
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
