Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2024-12, with the labels that each got.

#922 Readd support for deploying admission controller in local extensions setup
  charts/gardener-extension-admission-openstack/charts/application/templates/serviceaccount.yaml
  charts/gardener-extension-admission-openstack/charts/application/values.yaml
  charts/gardener-extension-admission-openstack/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-openstack/charts/runtime/values.yaml
Labels: area/dev-productivity, kind/task, needs/ok-to-test, needs/review, platform/openstack, size/xs

#917 fix(openstack/networking): filter router interfaces by all possible owners (#284)
  pkg/openstack/client/networking.go
Labels: area/networking, kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#923 re-add missing patch permission to csi-provisioner
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-provisioner.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#924 [Release v1.43] re-add missing patch permission to csi-provisioner
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-provisioner.yaml
Labels: area/storage, kind/bug, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/xs

#930 Use Subresource to mutate NamespacedCloudProfile status
  pkg/admission/mutator/webhook.go
Labels: area/usability, kind/bug, needs/ok-to-test, needs/review, platform/openstack, size/xs

#933 Update gardener to v1.110.0
  example/20-crd-druid.gardener.cloud_etcds.yaml
  example/20-crd-extensions.gardener.cloud_workers.yaml
  go.mod
  go.sum
  pkg/admission/validator/cloudprofile.go
  pkg/admission/validator/shoot.go
  pkg/cmd/options.go
  pkg/webhook/cloudprovider/ensurer.go
  pkg/webhook/controlplane/ensurer.go
  pkg/webhook/infrastructure/mutator.go
Labels: area/usability, kind/cleanup, needs/ok-to-test, needs/second-opinion, platform/openstack, size/l

#939 Hotfix - cherry pick mcm update
  imagevector/images.yaml
Labels: area/robustness, kind/bug, needs/ok-to-test, needs/review, platform/openstack, size/xs

#938 Remove VPA for the csi-driver-node and csi-driver-manila-node DaemonSets
  charts/internal/shoot-system-components/charts/csi-driver-manila/templates/vpa-node.yaml
  charts/internal/shoot-system-components/charts/csi-driver-manila/values.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
  charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
  pkg/controller/controlplane/valuesprovider.go
  pkg/controller/controlplane/valuesprovider_test.go
Labels: kind/enhancement, needs/ok-to-test, needs/review, platform/openstack, size/s, area/auto-scaling

#942 Hotfix 1.43 - cherry pick mcm update
  imagevector/images.yaml
Labels: area/robustness, kind/bug, needs/ok-to-test, needs/review, platform/openstack, size/xs
