Repository gardener/gardener-extension-provider-openstack, pull requests merged in 2025-09, with the labels that each got.

#1085 Fix failure because of race conditions for `update-resolv-conf.service`
  pkg/webhook/controlplane/ensurer.go
  pkg/webhook/controlplane/ensurer_test.go
Labels: area/high-availability, area/ops-productivity, kind/bug, kind/enhancement, needs/ok-to-test, platform/openstack, reviewed/ok-to-test, reviewed/lgtm, size/xs

#1143 add fixes for gha
  .github/workflows/non-release.yaml
Labels: needs/ok-to-test, platform/openstack, reviewed/lgtm, size/xs

#1141 Adjust required permissions for `upgrade-dependencies.yaml` workflow
  .github/workflows/upgrade-dependencies.yaml
Labels: needs/ok-to-test, needs/review, platform/openstack, size/xs

#1136 Add generation for `Extension` example
  Makefile
  example/doc.go
  example/extension.yaml
  example/extension/base/extension.yaml
  example/extension/base/kustomization.yaml
  example/extension/kustomization.yaml
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, needs/review, platform/openstack, size/m, area/ipcei

#1153 Add conformance test badge for Kubernetes v1.33
  README.md
Labels: needs/ok-to-test

#1098 Enhance user error classification
  pkg/apis/openstack/helper/error_codes.go
  pkg/apis/openstack/helper/helper_test.go
Labels: area/ops-productivity, kind/enhancement, needs/ok-to-test, needs/review, platform/openstack, reviewed/lgtm, size/xs

#1149 Add Github actions build on workflow_dispatch
  .github/workflows/non-release.yaml
Labels: area/quality, kind/enhancement, needs/ok-to-test, needs/review, platform/openstack, size/xs

#1157 Sync GHAs with other providers
  .github/workflows/non-release.yaml
  .github/workflows/pullrequest-trust-helper.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#1159 integration test gha
  .github/workflows/build.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release.yaml
Labels: needs/ok-to-test, platform/openstack, reviewed/lgtm, size/m

#1160 Increase infrastructure-test timeout
  .test-defs/infrastructure-test.yaml
Labels: area/quality, kind/enhancement, needs/ok-to-test, needs/review, platform/openstack, size/xs
